name: CI

on: [push]

jobs:
  build:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install deps
        run: sudo apt-get update && sudo apt-get install -y libpcap-dev

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Build
        run: go build -v ./...

      - name: Vet
        run: go vet -v ./...

      - name: Test
        run: go test -v ./...
